[[ISSUERS]]
address = "rPdoK8S6skUohpzTpabMJtrQH6ii15tWtx"
name = "DONTBUY"

[[TOKENS]]
issuer = "raP7o5zVFyZNbNybmriT3YSAkQ4xqNLHMN"
currency = "DONTBUY"
name = "DONTBUY"
desc = "This coin shouldn't exist"
icon = "https://dontbuy.wtf/dontbuy.png"

[[TOKENS.URLS]]
url = "https://dontbuy.wtf"
type = "website"

[[TOKENS.URLS]]
url = "https://x.com/dontbuywtf"
type = "social"

[[TOKENS.URLS]]
url = "https://t.me/dontbuyxrpl"
type = "social"
